//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motion_Joystick.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Motion_Joystick.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open source project.
        /// </summary>
        internal static string abouttitle {
            get {
                return ResourceManager.GetString("abouttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarification of settings.
        /// </summary>
        internal static string abouttitle1 {
            get {
                return ResourceManager.GetString("abouttitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh rate: Controls how fast per second the accelerometer data is sent to the computer..
        /// </summary>
        internal static string abouttitle2 {
            get {
                return ResourceManager.GetString("abouttitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low pass reduction: Controls how much the software should respond to inaccuracy in the accelerometer values, higher values ​​mean more vibration, very small values ​​result in a dead zone effect..
        /// </summary>
        internal static string abouttitle3 {
            get {
                return ResourceManager.GetString("abouttitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Sensitivity: Controls the sensitivity of the RT/LT accelerator and brake..
        /// </summary>
        internal static string abouttitle4 {
            get {
                return ResourceManager.GetString("abouttitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted Joystick: Turns the Joystick upside down for players with a smartphone with a broken screen..
        /// </summary>
        internal static string abouttitle5 {
            get {
                return ResourceManager.GetString("abouttitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Acceleration: When releasing the right trigger, the trigger position will not return to point 0, this also applies to fused triggers..
        /// </summary>
        internal static string abouttitle6 {
            get {
                return ResourceManager.GetString("abouttitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate on Interaction: When you press and release a button or trigger, a slight vibration is triggered to confirm input..
        /// </summary>
        internal static string abouttitle61 {
            get {
                return ResourceManager.GetString("abouttitle61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarification of inputs.
        /// </summary>
        internal static string abouttitle7 {
            get {
                return ResourceManager.GetString("abouttitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation of the left analog stick and triggers: The input is defined by the accelerometer and scroll bars..
        /// </summary>
        internal static string abouttitle8 {
            get {
                return ResourceManager.GetString("abouttitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Joystick.
        /// </summary>
        internal static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending packages to.
        /// </summary>
        internal static string Connected_to {
            get {
                return ResourceManager.GetString("Connected_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string Connection_Error {
            get {
                return ResourceManager.GetString("Connection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Lost.
        /// </summary>
        internal static string Connection_Lost {
            get {
                return ResourceManager.GetString("Connection_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection attempt timed out..
        /// </summary>
        internal static string Connection_to {
            get {
                return ResourceManager.GetString("Connection_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant Acceleration.
        /// </summary>
        internal static string ConstantAcceleration {
            get {
                return ResourceManager.GetString("ConstantAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Sending.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect after retries..
        /// </summary>
        internal static string Failed_tocon {
            get {
                return ResourceManager.GetString("Failed_tocon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device does not support Gyroscope, check if you have enough battery or the manufacturer&apos;s technical specifications..
        /// </summary>
        internal static string gyro_not_supported {
            get {
                return ResourceManager.GetString("gyro_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See instructions for connecting to Windows..
        /// </summary>
        internal static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address..
        /// </summary>
        internal static string Invalid_IP_address {
            get {
                return ResourceManager.GetString("Invalid_IP_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid port.
        /// </summary>
        internal static string Invalid_port {
            get {
                return ResourceManager.GetString("Invalid_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted Joystick.
        /// </summary>
        internal static string Inverted_Joystick {
            get {
                return ResourceManager.GetString("Inverted_Joystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Joystick.
        /// </summary>
        internal static string Motion_Joystick {
            get {
                return ResourceManager.GetString("Motion_Joystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to server..
        /// </summary>
        internal static string Not_Con {
            get {
                return ResourceManager.GetString("Not_Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Source Licenses.
        /// </summary>
        internal static string opensourcelicenses {
            get {
                return ResourceManager.GetString("opensourcelicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Saving Mode.
        /// </summary>
        internal static string PowerSavingMode {
            get {
                return ResourceManager.GetString("PowerSavingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Rate.
        /// </summary>
        internal static string Refresh_Rate_Label {
            get {
                return ResourceManager.GetString("Refresh_Rate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string repo {
            get {
                return ResourceManager.GetString("repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low pass reduction.
        /// </summary>
        internal static string Sensitivity {
            get {
                return ResourceManager.GetString("Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP Address.
        /// </summary>
        internal static string Server_IP_Address {
            get {
                return ResourceManager.GetString("Server_IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Settings_Value_Label {
            get {
                return ResourceManager.GetString("Settings_Value_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        internal static string T_Instructions {
            get {
                return ResourceManager.GetString("T_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Template - Full &amp; Wide.
        /// </summary>
        internal static string template_def1 {
            get {
                return ResourceManager.GetString("template_def1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Aviator - Inverted Face Buttons.
        /// </summary>
        internal static string template_def10 {
            get {
                return ResourceManager.GetString("template_def10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviator - with merged RT/LT.
        /// </summary>
        internal static string template_def11 {
            get {
                return ResourceManager.GetString("template_def11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviator RT/LT - Inverted Face Buttons.
        /// </summary>
        internal static string template_def12 {
            get {
                return ResourceManager.GetString("template_def12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Template - Full &amp; Wide (Inverted Pads).
        /// </summary>
        internal static string template_def2 {
            get {
                return ResourceManager.GetString("template_def2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sequential - Automotive.
        /// </summary>
        internal static string template_def3 {
            get {
                return ResourceManager.GetString("template_def3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Sequential - Automotive With Directional.
        /// </summary>
        internal static string template_def4 {
            get {
                return ResourceManager.GetString("template_def4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential - Automotive RT/LT separated.
        /// </summary>
        internal static string template_def5 {
            get {
                return ResourceManager.GetString("template_def5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential - Automotive RT/LT with directional.
        /// </summary>
        internal static string template_def6 {
            get {
                return ResourceManager.GetString("template_def6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Manual - Automotive.
        /// </summary>
        internal static string template_def7 {
            get {
                return ResourceManager.GetString("template_def7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Manual - Automotive, One Side RT/LT.
        /// </summary>
        internal static string template_def8 {
            get {
                return ResourceManager.GetString("template_def8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Aviator.
        /// </summary>
        internal static string template_def9 {
            get {
                return ResourceManager.GetString("template_def9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Default Aviator, but with the Face buttons reversed..
        /// </summary>
        internal static string template10des {
            get {
                return ResourceManager.GetString("template10des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to the Standard Aviator, but with combined left and right triggers..
        /// </summary>
        internal static string template11des {
            get {
                return ResourceManager.GetString("template11des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to the Aviator RT/LT, but with the face buttons reversed..
        /// </summary>
        internal static string template12des {
            get {
                return ResourceManager.GetString("template12des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This model has all the buttons and levers occupying the edges of the screen. .
        /// </summary>
        internal static string template1des {
            get {
                return ResourceManager.GetString("template1des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to the standard model, but with binary buttons in inverted positions..
        /// </summary>
        internal static string template2des {
            get {
                return ResourceManager.GetString("template2des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal for comfortable driving, semi-automatic gear shifting..
        /// </summary>
        internal static string template3des {
            get {
                return ResourceManager.GetString("template3des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to Default Sequential, but with the right analog stick in place of the D-Pad..
        /// </summary>
        internal static string template4des {
            get {
                return ResourceManager.GetString("template4des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal for comfortable driving, semi-automatic gear shifting. With separate accelerator and brake..
        /// </summary>
        internal static string template5des {
            get {
                return ResourceManager.GetString("template5des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to the RT/LT Automotive Sequential, but with directional pad instead of D-PAD.
        /// </summary>
        internal static string template6des {
            get {
                return ResourceManager.GetString("template6des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal for simulating a car&apos;s manual gear control..
        /// </summary>
        internal static string template7des {
            get {
                return ResourceManager.GetString("template7des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar to Default Manual - Automotive, but with accelerator and brake on one side..
        /// </summary>
        internal static string template8des {
            get {
                return ResourceManager.GetString("template8des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal model for aviation-related games, including all buttons in the largest possible comfortable space..
        /// </summary>
        internal static string template9des {
            get {
                return ResourceManager.GetString("template9des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string Templates {
            get {
                return ResourceManager.GetString("Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Sensitivity.
        /// </summary>
        internal static string TriggerSensitivity {
            get {
                return ResourceManager.GetString("TriggerSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to reconnect....
        /// </summary>
        internal static string Trying_to_reconnect {
            get {
                return ResourceManager.GetString("Trying to reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate when interacting.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
    }
}
