#namespace not imported
import sys
import os
import plyvel


if getattr(sys, 'frozen', False):  #-----ATUALIZADO-----
        # Executando como executable (PyInstaller)
    path = os.path.join(os.path.dirname(sys.executable), 'Localization')
else:
    # Executando como  script .py
    path = os.path.join(os.path.dirname(os.path.abspath(sys.argv[0])), 'Localization')

os.makedirs(path, exist_ok=True)

db = plyvel.DB(os.path.join(path, 'Localizations'), create_if_missing=True)

#en
db.put(b'en_arch', b'Architecture information not available.')
db.put(b'en_error', b'Error')
db.put(b'en_connected', b'Connected')
db.put(b'en_con_made', b'Connection established to')
db.put(b'en_listening_on', b'Listening on')
db.put(b'en_acept_con', b'Accepted connection from')
db.put(b'en_con_running', b'Connected. Running!')
db.put(b'en_gamepad_fail', b'Error creating virtual gamepad for')
db.put(b'en_gamepad_fail_title', b'Gamepad Error')
db.put(b'en_gamepad_fail_desc', b'Please check if the driver is installed correctly.')
db.put(b'en_disconnected', b'Disconnected')
db.put(b'en_disconnected_dedc', b'Connection closed for')
db.put(b'en_work', b'Working!')
db.put(b'en_client', b'Client')
db.put(b'en_server', b'Server')
db.put(b'en_server_to', b'timed out. Disconnecting.')
db.put(b'en_server_to_desc', b'Please check your network connection and try again.')
db.put(b'en_server_process_data', b'Error processing data from')
db.put(b'en_server_err_from', b'Error from')
db.put(b'en_title', b'Motion Joystick')
db.put(b'en_exit', b'Exit')
db.put(b'en_exit_desc', b'Are you sure you want to exit?')
db.put(b'en_exit_title', b'Exit Confirmation')
db.put(b'en_yes', b'Yes')
db.put(b'en_no', b'No')
db.put(b'en_settings', b'Settings')
db.put(b'en_menu', b'Menu')
db.put(b'en_title2', b'Wireless Motion Joystick')
db.put(b'en_alert', b'Alert')
db.put(b'en_warning', b'Warning')
db.put(b'en_restart_desc', b'Please restart the application to apply the changes.')
db.put(b'en_restart_title', b'Restart Required')
db.put(b'en_listen_seto', b'Listening set to:')
db.put(b'en_con_joys', b'Connected Controllers')
db.put(b'en_wheel_turn_range', b'Steering wheel Turn Range:')
db.put(b'en_wheel_direct_input', b'Steering wheel Direct Input:')
db.put(b'en_attention', b'Attention')
db.put(b'en_attention_desc', b'Motion Joystick Receiver started in background, right click taskbar icon to restore.')
db.put(b'en_reset', b'Reset')
db.put(b'en_sthidden', b'Start Hidden')

#de
db.put(b'de_arch', 'Architekturinformationen nicht verfügbar.'.encode('utf-8'))
db.put(b'de_error', 'Fehler'.encode('utf-8'))
db.put(b'de_connected', 'Verbunden'.encode('utf-8'))
db.put(b'de_con_made', 'Verbindung hergestellt zu'.encode('utf-8'))
db.put(b'de_listening_on', 'Lauscht auf'.encode('utf-8'))
db.put(b'de_acept_con', 'Verbindung akzeptiert von'.encode('utf-8'))
db.put(b'de_con_running', 'Verbunden. Läuft!'.encode('utf-8'))
db.put(b'de_gamepad_fail', 'Fehler beim Erstellen des virtuellen Gamepads für'.encode('utf-8'))
db.put(b'de_gamepad_fail_title', 'Gamepad-Fehler'.encode('utf-8'))
db.put(b'de_gamepad_fail_desc', 'Bitte überprüfen Sie, ob der Treiber korrekt installiert ist.'.encode('utf-8'))
db.put(b'de_disconnected', 'Getrennt'.encode('utf-8'))
db.put(b'de_disconnected_dedc', 'Verbindung getrennt für'.encode('utf-8'))
db.put(b'de_work', 'Funktioniert!'.encode('utf-8'))
db.put(b'de_client', 'Client'.encode('utf-8'))
db.put(b'de_server', 'Server'.encode('utf-8'))
db.put(b'de_server_to', 'Zeitüberschreitung. Trennung.'.encode('utf-8'))
db.put(b'de_server_to_desc', 'Bitte überprüfen Sie Ihre Netzwerkverbindung und versuchen Sie es erneut.'.encode('utf-8'))
db.put(b'de_server_process_data', 'Fehler bei der Datenverarbeitung von'.encode('utf-8'))
db.put(b'de_server_err_from', 'Fehler von'.encode('utf-8'))
db.put(b'de_title', 'Motion-Joystick'.encode('utf-8'))
db.put(b'de_exit', 'Beenden'.encode('utf-8'))
db.put(b'de_exit_desc', 'Möchten Sie wirklich beenden?'.encode('utf-8'))
db.put(b'de_exit_title', 'Beenden bestätigen'.encode('utf-8'))
db.put(b'de_yes', 'Ja'.encode('utf-8'))
db.put(b'de_no', 'Nein'.encode('utf-8'))
db.put(b'de_settings', 'Einstellungen'.encode('utf-8'))
db.put(b'de_menu', 'Menü'.encode('utf-8'))
db.put(b'de_title2', 'Kabelloser Motion-Joystick'.encode('utf-8'))
db.put(b'de_alert', 'Alarm'.encode('utf-8'))
db.put(b'de_warning', 'Warnung'.encode('utf-8'))
db.put(b'de_restart_desc', 'Bitte starten Sie die Anwendung neu, um die Änderungen anzuwenden.'.encode('utf-8'))
db.put(b'de_restart_title', 'Neustart erforderlich'.encode('utf-8'))
db.put(b'de_listen_seto', 'Lauschen eingestellt auf:'.encode('utf-8'))
db.put(b'de_con_joys', 'Verbundene Controller'.encode('utf-8'))
db.put(b'de_wheel_turn_range', 'Lenkrad-Drehbereich:'.encode('utf-8'))
db.put(b'de_wheel_direct_input', 'Lenkrad Direct Input:'.encode('utf-8'))
db.put(b'de_attention', 'Achtung'.encode('utf-8'))
db.put(b'de_attention_desc', 'Motion Joystick Receiver im Hintergrund gestartet, mit Rechtsklick auf das Taskleistensymbol wiederherstellen.'.encode('utf-8'))
db.put(b'de_reset', 'Zurücksetzen'.encode('utf-8'))
db.put(b'de_sthidden', 'Im Hintergrund starten'.encode('utf-8'))

#es
db.put(b'es_arch', 'Información de arquitectura no disponible.'.encode('utf-8'))
db.put(b'es_error', 'Error'.encode('utf-8'))
db.put(b'es_connected', 'Conectado'.encode('utf-8'))
db.put(b'es_con_made', 'Conexión establecida con'.encode('utf-8'))
db.put(b'es_listening_on', 'Escuchando en'.encode('utf-8'))
db.put(b'es_acept_con', 'Conexión aceptada de'.encode('utf-8'))
db.put(b'es_con_running', 'Conectado. ¡Ejecutando!'.encode('utf-8'))
db.put(b'es_gamepad_fail', 'Error al crear el gamepad virtual para'.encode('utf-8'))
db.put(b'es_gamepad_fail_title', 'Error de Gamepad'.encode('utf-8'))
db.put(b'es_gamepad_fail_desc', 'Por favor, verifique si el controlador está correctamente instalado.'.encode('utf-8'))
db.put(b'es_disconnected', 'Desconectado'.encode('utf-8'))
db.put(b'es_disconnected_dedc', 'Conexión cerrada para'.encode('utf-8'))
db.put(b'es_work', '¡Funcionando!'.encode('utf-8'))
db.put(b'es_client', 'Cliente'.encode('utf-8'))
db.put(b'es_server', 'Servidor'.encode('utf-8'))
db.put(b'es_server_to', 'Tiempo agotado. Desconectando.'.encode('utf-8'))
db.put(b'es_server_to_desc', 'Por favor, revise su conexión de red e intente nuevamente.'.encode('utf-8'))
db.put(b'es_server_process_data', 'Error procesando datos de'.encode('utf-8'))
db.put(b'es_server_err_from', 'Error de'.encode('utf-8'))
db.put(b'es_title', 'Motion Joystick'.encode('utf-8'))
db.put(b'es_exit', 'Salir'.encode('utf-8'))
db.put(b'es_exit_desc', '¿Está seguro de que desea salir?'.encode('utf-8'))
db.put(b'es_exit_title', 'Confirmación de salida'.encode('utf-8'))
db.put(b'es_yes', 'Sí'.encode('utf-8'))
db.put(b'es_no', 'No'.encode('utf-8'))
db.put(b'es_settings', 'Configuración'.encode('utf-8'))
db.put(b'es_menu', 'Menú'.encode('utf-8'))
db.put(b'es_title2', 'Joystick de Movimiento Inalámbrico'.encode('utf-8'))
db.put(b'es_alert', 'Alerta'.encode('utf-8'))
db.put(b'es_warning', 'Advertencia'.encode('utf-8'))
db.put(b'es_restart_desc', 'Por favor reinicie la aplicación para aplicar los cambios.'.encode('utf-8'))
db.put(b'es_restart_title', 'Reinicio requerido'.encode('utf-8'))
db.put(b'es_listen_seto', 'Escuchando configurado a:'.encode('utf-8'))
db.put(b'es_con_joys', 'Controladores conectados'.encode('utf-8'))
db.put(b'es_wheel_turn_range', 'Rango de giro del volante:'.encode('utf-8'))
db.put(b'es_wheel_direct_input', 'Entrada directa del volante:'.encode('utf-8'))
db.put(b'es_attention', 'Atención'.encode('utf-8'))
db.put(b'es_attention_desc', 'Motion Joystick Receiver se inició en segundo plano, haga clic derecho en el icono de la barra de tareas para restaurar.'.encode('utf-8'))
db.put(b'es_reset', 'Restablecer'.encode('utf-8'))
db.put(b'es_sthidden', 'Iniciar en segundo plano'.encode('utf-8'))

#it
db.put(b'it_arch', 'Informazioni sull’architettura non disponibili.'.encode('utf-8'))
db.put(b'it_error', 'Errore'.encode('utf-8'))
db.put(b'it_connected', 'Connesso'.encode('utf-8'))
db.put(b'it_con_made', 'Connessione stabilita a'.encode('utf-8'))
db.put(b'it_listening_on', 'In ascolto su'.encode('utf-8'))
db.put(b'it_acept_con', 'Connessione accettata da'.encode('utf-8'))
db.put(b'it_con_running', 'Connesso. In esecuzione!'.encode('utf-8'))
db.put(b'it_gamepad_fail', 'Errore nella creazione del gamepad virtuale per'.encode('utf-8'))
db.put(b'it_gamepad_fail_title', 'Errore Gamepad'.encode('utf-8'))
db.put(b'it_gamepad_fail_desc', 'Controlla che il driver sia installato correttamente.'.encode('utf-8'))
db.put(b'it_disconnected', 'Disconnesso'.encode('utf-8'))
db.put(b'it_disconnected_dedc', 'Connessione chiusa per'.encode('utf-8'))
db.put(b'it_work', 'Funziona!'.encode('utf-8'))
db.put(b'it_client', 'Client'.encode('utf-8'))
db.put(b'it_server', 'Server'.encode('utf-8'))
db.put(b'it_server_to', 'Timeout. Disconnessione.'.encode('utf-8'))
db.put(b'it_server_to_desc', 'Controlla la connessione di rete e riprova.'.encode('utf-8'))
db.put(b'it_server_process_data', 'Errore nell’elaborazione dei dati da'.encode('utf-8'))
db.put(b'it_server_err_from', 'Errore da'.encode('utf-8'))
db.put(b'it_title', 'Motion Joystick'.encode('utf-8'))
db.put(b'it_exit', 'Esci'.encode('utf-8'))
db.put(b'it_exit_desc', 'Sei sicuro di voler uscire?'.encode('utf-8'))
db.put(b'it_exit_title', 'Conferma uscita'.encode('utf-8'))
db.put(b'it_yes', 'Sì'.encode('utf-8'))
db.put(b'it_no', 'No'.encode('utf-8'))
db.put(b'it_settings', 'Impostazioni'.encode('utf-8'))
db.put(b'it_menu', 'Menu'.encode('utf-8'))
db.put(b'it_title2', 'Joystick di Movimento Wireless'.encode('utf-8'))
db.put(b'it_alert', 'Avviso'.encode('utf-8'))
db.put(b'it_warning', 'Attenzione'.encode('utf-8'))
db.put(b'it_restart_desc', 'Riavvia l’applicazione per applicare le modifiche.'.encode('utf-8'))
db.put(b'it_restart_title', 'Riavvio necessario'.encode('utf-8'))
db.put(b'it_listen_seto', 'Ascolto impostato su:'.encode('utf-8'))
db.put(b'it_con_joys', 'Controller connessi'.encode('utf-8'))
db.put(b'it_wheel_turn_range', 'Intervallo di sterzata:'.encode('utf-8'))
db.put(b'it_wheel_direct_input', 'Volante Direct Input:'.encode('utf-8'))
db.put(b'it_attention', 'Attenzione'.encode('utf-8'))
db.put(b'it_attention_desc', 'Motion Joystick Receiver avviato in background, fai clic con il tasto destro sull’icona nella barra delle applicazioni per ripristinarlo.'.encode('utf-8'))
db.put(b'it_reset', 'Ripristina'.encode('utf-8'))
db.put(b'it_sthidden', 'Avvia in background'.encode('utf-8'))

#ja
db.put(b'ja_arch', 'アーキテクチャ情報は利用できません。'.encode('utf-8'))
db.put(b'ja_error', 'エラー'.encode('utf-8'))
db.put(b'ja_connected', '接続されました'.encode('utf-8'))
db.put(b'ja_con_made', 'に接続されました'.encode('utf-8'))
db.put(b'ja_listening_on', 'リスニング中:'.encode('utf-8'))
db.put(b'ja_acept_con', 'からの接続を受け入れました'.encode('utf-8'))
db.put(b'ja_con_running', '接続済み。実行中！'.encode('utf-8'))
db.put(b'ja_gamepad_fail', '仮想ゲームパッドの作成に失敗しました:'.encode('utf-8'))
db.put(b'ja_gamepad_fail_title', 'ゲームパッドエラー'.encode('utf-8'))
db.put(b'ja_gamepad_fail_desc', 'ドライバが正しくインストールされているか確認してください。'.encode('utf-8'))
db.put(b'ja_disconnected', '切断されました'.encode('utf-8'))
db.put(b'ja_disconnected_dedc', '接続が切断されました:'.encode('utf-8'))
db.put(b'ja_work', '動作中！'.encode('utf-8'))
db.put(b'ja_client', 'クライアント'.encode('utf-8'))
db.put(b'ja_server', 'サーバー'.encode('utf-8'))
db.put(b'ja_server_to', 'タイムアウト。切断中。'.encode('utf-8'))
db.put(b'ja_server_to_desc', 'ネットワーク接続を確認して、再試行してください。'.encode('utf-8'))
db.put(b'ja_server_process_data', 'データ処理エラー:'.encode('utf-8'))
db.put(b'ja_server_err_from', 'エラー元:'.encode('utf-8'))
db.put(b'ja_title', 'モーションジョイスティック'.encode('utf-8'))
db.put(b'ja_exit', '終了'.encode('utf-8'))
db.put(b'ja_exit_desc', '本当に終了しますか？'.encode('utf-8'))
db.put(b'ja_exit_title', '終了の確認'.encode('utf-8'))
db.put(b'ja_yes', 'はい'.encode('utf-8'))
db.put(b'ja_no', 'いいえ'.encode('utf-8'))
db.put(b'ja_settings', '設定'.encode('utf-8'))
db.put(b'ja_menu', 'メニュー'.encode('utf-8'))
db.put(b'ja_title2', 'ワイヤレスモーションジョイスティック'.encode('utf-8'))
db.put(b'ja_alert', '警告'.encode('utf-8'))
db.put(b'ja_warning', '注意'.encode('utf-8'))
db.put(b'ja_restart_desc', '変更を適用するにはアプリケーションを再起動してください。'.encode('utf-8'))
db.put(b'ja_restart_title', '再起動が必要です'.encode('utf-8'))
db.put(b'ja_listen_seto', 'リスニング先:'.encode('utf-8'))
db.put(b'ja_con_joys', '接続されたコントローラー'.encode('utf-8'))
db.put(b'ja_wheel_turn_range', 'ステアリング範囲:'.encode('utf-8'))
db.put(b'ja_wheel_direct_input', 'ステアリング Direct Input:'.encode('utf-8'))
db.put(b'ja_attention', '注意'.encode('utf-8'))
db.put(b'ja_attention_desc', 'Motion Joystick Receiverはバックグラウンドで起動されました。タスクバーのアイコンを右クリックして復元してください。'.encode('utf-8'))
db.put(b'ja_reset', 'リセット'.encode('utf-8'))
db.put(b'ja_sthidden', 'バックグラウンドで開始'.encode('utf-8'))

#ru
db.put(b'ru_arch', 'Информация об архитектуре недоступна.'.encode('utf-8'))
db.put(b'ru_error', 'Ошибка'.encode('utf-8'))
db.put(b'ru_connected', 'Подключено'.encode('utf-8'))
db.put(b'ru_con_made', 'Установлено соединение с'.encode('utf-8'))
db.put(b'ru_listening_on', 'Ожидание на'.encode('utf-8'))
db.put(b'ru_acept_con', 'Принято соединение от'.encode('utf-8'))
db.put(b'ru_con_running', 'Подключено. Работает!'.encode('utf-8'))
db.put(b'ru_gamepad_fail', 'Ошибка создания виртуального геймпада для'.encode('utf-8'))
db.put(b'ru_gamepad_fail_title', 'Ошибка геймпада'.encode('utf-8'))
db.put(b'ru_gamepad_fail_desc', 'Пожалуйста, проверьте, правильно ли установлен драйвер.'.encode('utf-8'))
db.put(b'ru_disconnected', 'Отключено'.encode('utf-8'))
db.put(b'ru_disconnected_dedc', 'Соединение закрыто для'.encode('utf-8'))
db.put(b'ru_work', 'Работает!'.encode('utf-8'))
db.put(b'ru_client', 'Клиент'.encode('utf-8'))
db.put(b'ru_server', 'Сервер'.encode('utf-8'))
db.put(b'ru_server_to', 'Тайм-аут. Отключение.'.encode('utf-8'))
db.put(b'ru_server_to_desc', 'Проверьте сетевое подключение и повторите попытку.'.encode('utf-8'))
db.put(b'ru_server_process_data', 'Ошибка обработки данных от'.encode('utf-8'))
db.put(b'ru_server_err_from', 'Ошибка от'.encode('utf-8'))
db.put(b'ru_title', 'Motion Joystick'.encode('utf-8'))
db.put(b'ru_exit', 'Выход'.encode('utf-8'))
db.put(b'ru_exit_desc', 'Вы уверены, что хотите выйти?'.encode('utf-8'))
db.put(b'ru_exit_title', 'Подтверждение выхода'.encode('utf-8'))
db.put(b'ru_yes', 'Да'.encode('utf-8'))
db.put(b'ru_no', 'Нет'.encode('utf-8'))
db.put(b'ru_settings', 'Настройки'.encode('utf-8'))
db.put(b'ru_menu', 'Меню'.encode('utf-8'))
db.put(b'ru_title2', 'Беспроводной Motion Joystick'.encode('utf-8'))
db.put(b'ru_alert', 'Оповещение'.encode('utf-8'))
db.put(b'ru_warning', 'Предупреждение'.encode('utf-8'))
db.put(b'ru_restart_desc', 'Пожалуйста, перезапустите приложение для применения изменений.'.encode('utf-8'))
db.put(b'ru_restart_title', 'Требуется перезапуск'.encode('utf-8'))
db.put(b'ru_listen_seto', 'Прослушивание установлено на:'.encode('utf-8'))
db.put(b'ru_con_joys', 'Подключённые контроллеры'.encode('utf-8'))
db.put(b'ru_wheel_turn_range', 'Угол поворота руля:'.encode('utf-8'))
db.put(b'ru_wheel_direct_input', 'Руль Direct Input:'.encode('utf-8'))
db.put(b'ru_attention', 'Внимание'.encode('utf-8'))
db.put(b'ru_attention_desc', 'Motion Joystick Receiver запущен в фоновом режиме. Щёлкните правой кнопкой мыши по значку в панели задач, чтобы восстановить.'.encode('utf-8'))
db.put(b'ru_reset', 'Сброс'.encode('utf-8'))
db.put(b'ru_sthidden', 'Запуск в фоновом режиме'.encode('utf-8'))

#zh
db.put(b'zh_arch', '架构信息不可用。'.encode('utf-8'))
db.put(b'zh_error', '错误'.encode('utf-8'))
db.put(b'zh_connected', '已连接'.encode('utf-8'))
db.put(b'zh_con_made', '已建立连接到'.encode('utf-8'))
db.put(b'zh_listening_on', '监听端口：'.encode('utf-8'))
db.put(b'zh_acept_con', '已接受来自的连接'.encode('utf-8'))
db.put(b'zh_con_running', '已连接。运行中！'.encode('utf-8'))
db.put(b'zh_gamepad_fail', '创建虚拟手柄失败：'.encode('utf-8'))
db.put(b'zh_gamepad_fail_title', '手柄错误'.encode('utf-8'))
db.put(b'zh_gamepad_fail_desc', '请检查驱动程序是否正确安装。'.encode('utf-8'))
db.put(b'zh_disconnected', '已断开连接'.encode('utf-8'))
db.put(b'zh_disconnected_dedc', '连接已关闭：'.encode('utf-8'))
db.put(b'zh_work', '运行中！'.encode('utf-8'))
db.put(b'zh_client', '客户端'.encode('utf-8'))
db.put(b'zh_server', '服务器'.encode('utf-8'))
db.put(b'zh_server_to', '连接超时，正在断开。'.encode('utf-8'))
db.put(b'zh_server_to_desc', '请检查您的网络连接并重试。'.encode('utf-8'))
db.put(b'zh_server_process_data', '处理来自的数据时出错：'.encode('utf-8'))
db.put(b'zh_server_err_from', '来自的错误：'.encode('utf-8'))
db.put(b'zh_title', '动作摇杆'.encode('utf-8'))
db.put(b'zh_exit', '退出'.encode('utf-8'))
db.put(b'zh_exit_desc', '您确定要退出吗？'.encode('utf-8'))
db.put(b'zh_exit_title', '退出确认'.encode('utf-8'))
db.put(b'zh_yes', '是'.encode('utf-8'))
db.put(b'zh_no', '否'.encode('utf-8'))
db.put(b'zh_settings', '设置'.encode('utf-8'))
db.put(b'zh_menu', '菜单'.encode('utf-8'))
db.put(b'zh_title2', '无线动作摇杆'.encode('utf-8'))
db.put(b'zh_alert', '提示'.encode('utf-8'))
db.put(b'zh_warning', '警告'.encode('utf-8'))
db.put(b'zh_restart_desc', '请重新启动应用程序以应用更改。'.encode('utf-8'))
db.put(b'zh_restart_title', '需要重新启动'.encode('utf-8'))
db.put(b'zh_listen_seto', '监听设置为：'.encode('utf-8'))
db.put(b'zh_con_joys', '已连接的控制器'.encode('utf-8'))
db.put(b'zh_wheel_turn_range', '方向盘转动范围：'.encode('utf-8'))
db.put(b'zh_wheel_direct_input', '方向盘 Direct Input：'.encode('utf-8'))
db.put(b'zh_attention', '注意'.encode('utf-8'))
db.put(b'zh_attention_desc', 'Motion Joystick Receiver 已在后台启动，请右键点击任务栏图标以恢复。'.encode('utf-8'))
db.put(b'zh_reset', '重置'.encode('utf-8'))
db.put(b'zh_sthidden', '后台启动'.encode('utf-8'))

#pt
db.put(b'pt_arch', 'Informações de arquitetura não disponíveis.'.encode('utf-8'))
db.put(b'pt_error', 'Erro'.encode('utf-8'))
db.put(b'pt_connected', 'Conectado'.encode('utf-8'))
db.put(b'pt_con_made', 'Conexão estabelecida com'.encode('utf-8'))
db.put(b'pt_listening_on', 'Ouvindo em'.encode('utf-8'))
db.put(b'pt_acept_con', 'Conexão aceita de'.encode('utf-8'))
db.put(b'pt_con_running', 'Conectado. Em execução!'.encode('utf-8'))
db.put(b'pt_gamepad_fail', 'Erro ao criar o gamepad virtual para'.encode('utf-8'))
db.put(b'pt_gamepad_fail_title', 'Erro no Gamepad'.encode('utf-8'))
db.put(b'pt_gamepad_fail_desc', 'Verifique se o driver está instalado corretamente.'.encode('utf-8'))
db.put(b'pt_disconnected', 'Desconectado'.encode('utf-8'))
db.put(b'pt_disconnected_dedc', 'Conexão encerrada para'.encode('utf-8'))
db.put(b'pt_work', 'Funcionando!'.encode('utf-8'))
db.put(b'pt_client', 'Cliente'.encode('utf-8'))
db.put(b'pt_server', 'Servidor'.encode('utf-8'))
db.put(b'pt_server_to', 'tempo esgotado. Desconectando.'.encode('utf-8'))
db.put(b'pt_server_to_desc', 'Verifique sua conexão de rede e tente novamente.'.encode('utf-8'))
db.put(b'pt_server_process_data', 'Erro ao processar dados de'.encode('utf-8'))
db.put(b'pt_server_err_from', 'Erro de'.encode('utf-8'))
db.put(b'pt_title', 'Motion Joystick'.encode('utf-8'))
db.put(b'pt_exit', 'Sair'.encode('utf-8'))
db.put(b'pt_exit_desc', 'Tem certeza de que deseja sair?'.encode('utf-8'))
db.put(b'pt_exit_title', 'Confirmação de Saída'.encode('utf-8'))
db.put(b'pt_yes', 'Sim'.encode('utf-8'))
db.put(b'pt_no', 'Não'.encode('utf-8'))
db.put(b'pt_settings', 'Configurações'.encode('utf-8'))
db.put(b'pt_menu', 'Menu'.encode('utf-8'))
db.put(b'pt_title2', 'Joystick de Movimento Sem Fio'.encode('utf-8'))
db.put(b'pt_alert', 'Alerta'.encode('utf-8'))
db.put(b'pt_warning', 'Aviso'.encode('utf-8'))
db.put(b'pt_restart_desc', 'Reinicie o aplicativo para aplicar as alterações.'.encode('utf-8'))
db.put(b'pt_restart_title', 'Reinício Necessário'.encode('utf-8'))
db.put(b'pt_listen_seto', 'Escutando em:'.encode('utf-8'))
db.put(b'pt_con_joys', 'Controladores Conectados'.encode('utf-8'))
db.put(b'pt_wheel_turn_range', 'Giro do volante:'.encode('utf-8'))
db.put(b'pt_wheel_direct_input', 'Entrada Direta do volante:'.encode('utf-8'))
db.put(b'pt_attention', 'Atenção'.encode('utf-8'))
db.put(b'pt_attention_desc', 'Receptor Motion Joystick iniciado em segundo plano, clique com o botão direito no ícone da bandeja para restaurar.'.encode('utf-8'))
db.put(b'pt_reset', 'Redefinir'.encode('utf-8'))
db.put(b'pt_sthidden', 'Iniciar Oculto'.encode('utf-8'))

#hi
db.put(b'hi_arch', 'वास्तुकला की जानकारी उपलब्ध नहीं है।'.encode('utf-8'))
db.put(b'hi_error', 'त्रुटि'.encode('utf-8'))
db.put(b'hi_connected', 'कनेक्टेड'.encode('utf-8'))
db.put(b'hi_con_made', 'से कनेक्शन स्थापित हुआ'.encode('utf-8'))
db.put(b'hi_listening_on', 'सुन रहा है'.encode('utf-8'))
db.put(b'hi_acept_con', 'से कनेक्शन स्वीकार किया गया'.encode('utf-8'))
db.put(b'hi_con_running', 'कनेक्टेड। चालू है!'.encode('utf-8'))
db.put(b'hi_gamepad_fail', 'के लिए वर्चुअल गेमपैड बनाने में त्रुटि'.encode('utf-8'))
db.put(b'hi_gamepad_fail_title', 'गेमपैड त्रुटि'.encode('utf-8'))
db.put(b'hi_gamepad_fail_desc', 'कृपया जांचें कि ड्राइवर सही से स्थापित है या नहीं।'.encode('utf-8'))
db.put(b'hi_disconnected', 'डिस्कनेक्टेड'.encode('utf-8'))
db.put(b'hi_disconnected_dedc', 'के लिए कनेक्शन बंद किया गया'.encode('utf-8'))
db.put(b'hi_work', 'काम कर रहा है!'.encode('utf-8'))
db.put(b'hi_client', 'क्लाइंट'.encode('utf-8'))
db.put(b'hi_server', 'सर्वर'.encode('utf-8'))
db.put(b'hi_server_to', 'समय समाप्त। डिस्कनेक्ट कर रहा है।'.encode('utf-8'))
db.put(b'hi_server_to_desc', 'कृपया अपने नेटवर्क कनेक्शन की जाँच करें और पुनः प्रयास करें।'.encode('utf-8'))
db.put(b'hi_server_process_data', 'से डेटा प्रोसेस करते समय त्रुटि'.encode('utf-8'))
db.put(b'hi_server_err_from', 'से त्रुटि'.encode('utf-8'))
db.put(b'hi_title', 'मोशन जॉयस्टिक'.encode('utf-8'))
db.put(b'hi_exit', 'बाहर निकलें'.encode('utf-8'))
db.put(b'hi_exit_desc', 'क्या आप वाकई बाहर निकलना चाहते हैं?'.encode('utf-8'))
db.put(b'hi_exit_title', 'बाहर निकलने की पुष्टि'.encode('utf-8'))
db.put(b'hi_yes', 'हाँ'.encode('utf-8'))
db.put(b'hi_no', 'नहीं'.encode('utf-8'))
db.put(b'hi_settings', 'सेटिंग्स'.encode('utf-8'))
db.put(b'hi_menu', 'मेनू'.encode('utf-8'))
db.put(b'hi_title2', 'वायरलेस मोशन जॉयस्टिक'.encode('utf-8'))
db.put(b'hi_alert', 'चेतावनी'.encode('utf-8'))
db.put(b'hi_warning', 'सावधानी'.encode('utf-8'))
db.put(b'hi_restart_desc', 'परिवर्तनों को लागू करने के लिए एप्लिकेशन को पुनरारंभ करें।'.encode('utf-8'))
db.put(b'hi_restart_title', 'पुनरारंभ आवश्यक'.encode('utf-8'))
db.put(b'hi_listen_seto', 'सुन रहा है:'.encode('utf-8'))
db.put(b'hi_con_joys', 'कनेक्टेड कंट्रोलर'.encode('utf-8'))
db.put(b'hi_wheel_turn_range', 'स्टीयरिंग व्हील मोड़ सीमा:'.encode('utf-8'))
db.put(b'hi_wheel_direct_input', 'स्टीयरिंग व्हील डायरेक्ट इनपुट:'.encode('utf-8'))
db.put(b'hi_attention', 'ध्यान दें'.encode('utf-8'))
db.put(b'hi_attention_desc', 'मोशन जॉयस्टिक रिसीवर पृष्ठभूमि में शुरू हुआ, पुनः लाने के लिए टास्कबार आइकन पर राइट-क्लिक करें।'.encode('utf-8'))
db.put(b'hi_reset', 'रीसेट करें'.encode('utf-8'))
db.put(b'hi_sthidden', 'छिपाकर शुरू करें'.encode('utf-8'))

#fr
db.put(b'fr_arch', 'Informations sur l’architecture non disponibles.'.encode('utf-8'))
db.put(b'fr_error', 'Erreur'.encode('utf-8'))
db.put(b'fr_connected', 'Connecté'.encode('utf-8'))
db.put(b'fr_con_made', 'Connexion établie avec'.encode('utf-8'))
db.put(b'fr_listening_on', 'Écoute sur'.encode('utf-8'))
db.put(b'fr_acept_con', 'Connexion acceptée de'.encode('utf-8'))
db.put(b'fr_con_running', 'Connecté. En cours d’exécution !'.encode('utf-8'))
db.put(b'fr_gamepad_fail', 'Erreur lors de la création du gamepad virtuel pour'.encode('utf-8'))
db.put(b'fr_gamepad_fail_title', 'Erreur Gamepad'.encode('utf-8'))
db.put(b'fr_gamepad_fail_desc', 'Veuillez vérifier si le pilote est correctement installé.'.encode('utf-8'))
db.put(b'fr_disconnected', 'Déconnecté'.encode('utf-8'))
db.put(b'fr_disconnected_dedc', 'Connexion fermée pour'.encode('utf-8'))
db.put(b'fr_work', 'Fonctionne !'.encode('utf-8'))
db.put(b'fr_client', 'Client'.encode('utf-8'))
db.put(b'fr_server', 'Serveur'.encode('utf-8'))
db.put(b'fr_server_to', 'temps écoulé. Déconnexion.'.encode('utf-8'))
db.put(b'fr_server_to_desc', 'Veuillez vérifier votre connexion réseau et réessayer.'.encode('utf-8'))
db.put(b'fr_server_process_data', 'Erreur lors du traitement des données de'.encode('utf-8'))
db.put(b'fr_server_err_from', 'Erreur de'.encode('utf-8'))
db.put(b'fr_title', 'Motion Joystick'.encode('utf-8'))
db.put(b'fr_exit', 'Quitter'.encode('utf-8'))
db.put(b'fr_exit_desc', 'Êtes-vous sûr de vouloir quitter ?'.encode('utf-8'))
db.put(b'fr_exit_title', 'Confirmation de sortie'.encode('utf-8'))
db.put(b'fr_yes', 'Oui'.encode('utf-8'))
db.put(b'fr_no', 'Non'.encode('utf-8'))
db.put(b'fr_settings', 'Paramètres'.encode('utf-8'))
db.put(b'fr_menu', 'Menu'.encode('utf-8'))
db.put(b'fr_title2', 'Joystick de Mouvement Sans Fil'.encode('utf-8'))
db.put(b'fr_alert', 'Alerte'.encode('utf-8'))
db.put(b'fr_warning', 'Avertissement'.encode('utf-8'))
db.put(b'fr_restart_desc', 'Veuillez redémarrer l’application pour appliquer les modifications.'.encode('utf-8'))
db.put(b'fr_restart_title', 'Redémarrage requis'.encode('utf-8'))
db.put(b'fr_listen_seto', 'Écoute définie sur :'.encode('utf-8'))
db.put(b'fr_con_joys', 'Contrôleurs connectés'.encode('utf-8'))
db.put(b'fr_wheel_turn_range', 'Plage de rotation du volant :'.encode('utf-8'))
db.put(b'fr_wheel_direct_input', 'Entrée directe du volant :'.encode('utf-8'))
db.put(b'fr_attention', 'Attention'.encode('utf-8'))
db.put(b'fr_attention_desc', 'Récepteur Motion Joystick lancé en arrière-plan, clic droit sur l’icône de la barre des tâches pour restaurer.'.encode('utf-8'))
db.put(b'fr_reset', 'Réinitialiser'.encode('utf-8'))
db.put(b'fr_sthidden', 'Démarrer caché'.encode('utf-8'))